#!/bin/bash

if [[ $(uname -r) == *"Microsoft"* ]]; then
  #echo Npm Windows
  docker run --rm -ti -w /var/www -v ${PWD/\/mnt/''}:/var/www node:8.11 npm $@
else
  #echo Npm Linux
  docker run --rm -ti -w /var/www -v $(pwd):/var/www node:8.11 npm $@
fi
